// <auto-generated />
using AyuLanka.AMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AyuLanka.AMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AyuLanka.AMS.DataModels.AppointmentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactNo")
                        .HasColumnType("int");

                    b.Property<int>("CustomerName")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EnteredBy")
                        .HasColumnType("int");

                    b.Property<int>("EnteredDate")
                        .HasColumnType("int");

                    b.Property<int>("FromTime")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleDate")
                        .HasColumnType("int");

                    b.Property<int>("ToTime")
                        .HasColumnType("int");

                    b.Property<int>("TokenIssueTime")
                        .HasColumnType("int");

                    b.Property<int>("TokenNo")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TreatmentTypeId");

                    b.ToTable("AppointmentSchedules");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.DayOffChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOffChangeMasterId")
                        .HasColumnType("int");

                    b.Property<int>("IsDayOffPost")
                        .HasColumnType("int");

                    b.Property<int>("IsDayOffPre")
                        .HasColumnType("int");

                    b.Property<int>("StaffRosterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayOffChangeMasterId");

                    b.HasIndex("StaffRosterId");

                    b.ToTable("DayOffChangeLogs");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.DayOffChangeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeTo")
                        .HasColumnType("int");

                    b.Property<int>("ChangeWith")
                        .HasColumnType("int");

                    b.Property<int>("DayOffChangeReasonId")
                        .HasColumnType("int");

                    b.Property<int>("StaffRosterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayOffChangeReasonId");

                    b.HasIndex("StaffRosterId");

                    b.ToTable("DayOffChangeMasters");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.DayOffChangeReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DayOffChangeReasons");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FullName")
                        .HasColumnType("int");

                    b.Property<int>("JoinedDate")
                        .HasColumnType("int");

                    b.Property<int>("NIC")
                        .HasColumnType("int");

                    b.Property<int>("ShiftMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("ShiftMasterId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.ShiftMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromTime")
                        .HasColumnType("int");

                    b.Property<int>("ToTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShiftMasters");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.StaffAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceDate")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("InTime")
                        .HasColumnType("int");

                    b.Property<int>("OutTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("StaffAttendances");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.StaffLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FromDate")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<int>("ToDate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("StaffLeaves");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.StaffRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("IsDayOff")
                        .HasColumnType("int");

                    b.Property<int>("RosterDate")
                        .HasColumnType("int");

                    b.Property<int>("ShiftMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftMasterId");

                    b.ToTable("StaffRosters");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.TreatmentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TreatmentTypeId");

                    b.ToTable("TreatmentLocations");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.TreatmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TreatmentTypes");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.AppointmentSchedule", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.TreatmentType", "TreatmentType")
                        .WithMany()
                        .HasForeignKey("TreatmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TreatmentType");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.DayOffChangeLog", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.DayOffChangeMaster", "DayOffChangeMaster")
                        .WithMany()
                        .HasForeignKey("DayOffChangeMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.StaffRoster", "StaffRoster")
                        .WithMany()
                        .HasForeignKey("StaffRosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayOffChangeMaster");

                    b.Navigation("StaffRoster");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.DayOffChangeMaster", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.DayOffChangeReason", "DayOffChangeReason")
                        .WithMany()
                        .HasForeignKey("DayOffChangeReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.StaffRoster", "StaffRoster")
                        .WithMany()
                        .HasForeignKey("StaffRosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayOffChangeReason");

                    b.Navigation("StaffRoster");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.Employee", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.ShiftMaster", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Designation");

                    b.Navigation("EmploymentType");

                    b.Navigation("ShiftMaster");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.StaffAttendance", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.StaffLeave", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.StaffRoster", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.ShiftMaster", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ShiftMaster");
                });

            modelBuilder.Entity("AyuLanka.AMS.DataModels.TreatmentLocation", b =>
                {
                    b.HasOne("AyuLanka.AMS.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyuLanka.AMS.DataModels.TreatmentType", "TreatmentType")
                        .WithMany()
                        .HasForeignKey("TreatmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("TreatmentType");
                });
#pragma warning restore 612, 618
        }
    }
}
